const express = require('express');
const { getCTrainees, updatePassword, postCourseRegister, getCTrainee, getCTraineeCourses, login, logout, checkHaveAccess, checkCourseProgress, findExamGrade, findExercisesGrade, checkExercisesSolvingStatus, checkSolvingStatus, updateExercisesGrade, updateSolvedExercises, updateCourseProgress, updateSolvedExam, updateExamGrade } = require('../Controllers/corpTraineeController');
const router = express.Router();

router.get('/', getCTrainees);
router.get('/:id', getCTrainee);
router.get('/getcourses/:id', getCTraineeCourses);
router.patch('/password/:id', updatePassword);
router.post('/register/:id', postCourseRegister);
router.post('/login', login);
router.get('/logout', logout);
router.post('/checkaccess/:id', checkHaveAccess);
router.post('/courseprogress/:id', checkCourseProgress);
router.post('/findgrade/:id', findExercisesGrade);
router.post('/findtestgrade/:id', findExamGrade);
router.post('/checkexstatus/:id', checkExercisesSolvingStatus);
router.post('/checkstatus/:id', checkSolvingStatus);
router.post('/updateexamgrade/:id', updateExamGrade);
router.post('/updateexercisesgrade/:id', updateExercisesGrade);
router.post('/updateexercisesstatus/:id', updateSolvedExercises);
router.post('/updateprogress/:id', updateCourseProgress);
router.post('/updateexamstatus/:id', updateSolvedExam);
module.exports = router;